export const PROVIDERS_REPOSITORY = {
  SEQUELIZE: 'SEQUELIZE',
  USERS_REPOSITORY: 'USERS_REPOSITORY',
  USERS_FOLLOW_REPOSITORY: 'USERS_FOLLOW_REPOSITORY',
  VIDEOS_REPOSITORY: 'VIDEOS_REPOSITORY',
  INTERACTIONS_REPOSITORY: 'INTERACTIONS_REPOSITORY',
  APP_GUARD: 'APP_GUARD',
};
